### ISSUE TITLE
fonts

### ISSUE THREAD

**Issue by klortiz13** [klortiz13/sp24-cse110-lab3#14]
On this branch, you must:
- [x] Include and use **a** third party font

https://fonts.google.com/
 *Can load font in either your HTML or CSS.

**Comment by MohdHasan2502** [comment]
what I have to do. I don't understand what are you trying to say .

**Comment by klortiz13** [comment]
> what I have to do. I don't understand what are you trying to say .

I'm not talking to you, this is my personal project. Stay away :)
